### ISSUE TITLE
Long URL issues?

### ISSUE THREAD

**Issue by semaf** [neocotic/yourls-api#11]
If I expand the shortend url than I can see that the url is getting the %2 etc characters which cant be recognized as shortend url.

`https://doma.in/yourls-api.php?callback=__yourls1484561232771_jsonp%5B1484561232773%5D&format=jsonp&signature=12345678&action=expand&shorturl=https%3A%2F%2Fwww.domain.com%2Fmobile%2FiPhone-6-LCD-Display-with-Touchscreen-Black`

It is ok that for the Domain: _**https%3A%2F%2Fwww.domain.com%2Fmobile%2FiPhone-6-LCD-Display-with-Touchscreen-Black**_ does not exist a shorten url.

The answer from jsonp
`__yourls12345678_jsonp[12345678]({"keyword":"httpswwwdomaincommobileihone6isplaywithouchscreenlack","message":"Error: short URL not found","errorCode":404,"callback":"__yourls1484561232771_jsonp[12345678]"})`

If you check the keyword than you will see it is also missing some letters like **p, d, t or b**

Regards

**Comment by airmrcr** [comment]
I'm not sure if/how this is an issue with this library. Can you please paste your code here?

I'm going to guess that `https://www.domain.com/mobile/iPhone-6-LCD-Display-with-Touchscreen-Black` is the *long* URL and that you're trying to expand it, however, you can only expand *short* URLs. See the [YOURLS API documentation](https://yourls.org/#API) for more information. This would explain why you're getting that error since the YOURLS server will see that the `shorturl` doesn't match the YOURLS server hostname so will try to sanitize it into a short URL, which is why a bunch of characters have been stripped.

Please see the README section for expanding short URLs for more information:
https://github.com/neocotic/yourls-api#expanding

I'm going to close this right now as it doesn't appear to be a bug with this library.
